# Generated by Django 4.2.7 on 2026-01-18 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_requirements', models.TextField(blank=True, help_text="Customer's dietary requirements or allergies", null=True)),
                ('special_requests', models.TextField(blank=True, help_text='Default special requests for bookings', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Profile creation timestamp')),
                ('user', models.OneToOneField(help_text='Linked user account', on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
