# Generated by Django 4.2.7 on 2026-01-18 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name (e.g., Vegetarian)', max_length=50, unique=True)),
                ('icon', models.CharField(help_text='Emoji or icon (e.g., 🌱)', max_length=10)),
            ],
            options={
                'verbose_name': 'Dietary Tag',
                'verbose_name_plural': 'Dietary Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Starters, Mains)', max_length=100)),
                ('display_order', models.IntegerField(default=0, help_text='Order to display categories (0 = first)')),
            ],
            options={
                'verbose_name': 'Menu Category',
                'verbose_name_plural': 'Menu Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Dish name', max_length=200)),
                ('description', models.TextField(help_text='Dish description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in GBP (e.g., 12.50)', max_digits=5)),
                ('is_available', models.BooleanField(default=True, help_text='Is this item currently available?')),
                ('image', models.ImageField(blank=True, help_text='Optional dish photo', null=True, upload_to='menu_items/')),
                ('category', models.ForeignKey(help_text='Menu category (Starters, Mains, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menucategory')),
                ('dietary_info', models.ManyToManyField(blank=True, help_text='Dietary tags (Vegetarian, Vegan, etc.)', related_name='menu_items', to='menu.dietarytag')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['category__display_order', 'name'],
            },
        ),
    ]
