# Generated by Django 4.2.7 on 2026-01-18 13:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(help_text='Physical table number (must be unique)', unique=True)),
                ('capacity', models.IntegerField(help_text='Maximum number of guests', validators=[django.core.validators.MinValueValidator(1)])),
                ('location', models.CharField(choices=[('Window', 'Window'), ('Corner', 'Corner'), ('Centre', 'Centre'), ('Private', 'Private')], default='Centre', help_text='Table location in restaurant', max_length=20)),
                ('is_available', models.BooleanField(default=True, help_text='Is table available for bookings?')),
                ('description', models.TextField(blank=True, help_text='Additional notes about the table')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['table_number'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(help_text='Booking time (e.g., 19:00)')),
                ('max_capacity', models.IntegerField(blank=True, help_text='Maximum total guests for this time slot (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this time slot available for bookings?')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(help_text='Date of reservation')),
                ('number_of_guests', models.IntegerField(help_text='Number of guests (1-8)', validators=[django.core.validators.MinValueValidator(1, message='At least 1 guest required'), django.core.validators.MaxValueValidator(8, message='Maximum 8 guests per booking')])),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Seated', 'Seated'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No-Show', 'No-Show')], default='Pending', help_text='Booking status', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Unique booking reference (auto-generated)', max_length=8, unique=True)),
                ('special_requests', models.TextField(blank=True, help_text='Customer special requests or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Booking creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Cancellation timestamp', null=True)),
                ('table', models.ForeignKey(blank=True, help_text='Assigned table (can be assigned later)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.table')),
                ('timeslot', models.ForeignKey(help_text='Reservation time slot', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.timeslot')),
                ('user', models.ForeignKey(help_text='Customer who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-booking_date', '-timeslot__time'],
                'unique_together': {('user', 'booking_date', 'timeslot')},
            },
        ),
    ]
